### ISSUE TITLE
Enable X-Ray tracing

### ISSUE THREAD

**Issue by adieuadieu** [adieuadieu/retinal#54]
`~/serverless.yml`:

```yaml

    # Enable X-Ray tracing on Lambda functions
    SharpLambdaFunction:
      Properties:
        TracingConfig:
          Mode: Active

```

- attach `AWSXrayWriteOnlyAccess` IAM policy.
- instrument AWS SDK calls ([more](https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html))

```js
var AWSXRay = require('aws-xray-sdk-core');
var AWS = AWSXRay.captureAWS(require('aws-sdk'));
```
